
# Data Cleaning Hyperparameters
SMA_PERIOD = 14
EMA_PERIOD = 14
RSI_PERIODS = [7, 14, 21]
MACD_FAST_PERIOD = 12
MACD_SLOW_PERIOD = 26
MACD_SIGNAL_PERIOD = 9
BBANDS_PERIOD = 20
BBANDS_NBDEVUP = 2
BBANDS_NBDEVDN = 2
ROLLING_WINDOW_48 = 48
ROLLING_WINDOW_288 = 288
PEAK_THRESHOLD = 0.005
TROUGH_THRESHOLD = 0.005
FORWARD_BUFFER = 0
BACKWARD_BUFFER = 0
NON_PEAK_REDUCTION_FACTOR = 10  # Adjust this value as needed
X_PREVIOUS_QUOTES = 10

# Data Splitting Hyperparameters
SEQUENCE_LENGTH = 288
TRAINING_DATA_PROPORTION = 0.9
SCALING_PRECISION = 3
TRAIN_SPLIT = .8
